### ISSUE TITLE
toolbar icon and dark theme - and a question

### ISSUE THREAD

**Issue by atomGit** [wooque/site-bleacher#2]
interesting extension

the toolbar icon is barely visible when using the default dark FF theme

also, what is the purpose of the "whitelist tab until close" option? does this mean that storage is not removed for a tab if the tab is closed/reopened until the browser is closed?

**Comment by wooque** [comment]
It's because icon was transparent, I filled it with white now.

Unfortunate wording, changed to "whitelist tab" only, means cookies won't be deleted on domain changes like it would be if tab is not whitelisted,  helps with sites where you are redirected to another domain for login.

Changes will be in 1.0.19 (d0e73fa337bef3cbbec4f7e5b1fabc4828897886)

**Comment by atomGit** [comment]
great - thanks

regarding the whitelist feature, thanks for explaining - that is a handy feature indeed

i'll let you close this issue if you see fit
